### ISSUE TITLE
12.6.0 installs `/usr/lib/python*/site-packages/tests`

### ISSUE THREAD

**Issue by mgorny** [jaraco/pip-run#98] opened 2024-02-09 03:24 UTC
After the turnaround from 3278b436995d9318c46c2037ad88f67503b2af59 and e18699537ad5536277884efa78fa7a485e78fef3, the package started installing `tests` straight into `site-packages`.

**Comment by mtelka** [comment] 2024-02-09 10:00
Here I also see `docs` directly in the `site-packages`.

**Comment by bswck** [comment] 2024-02-09 16:12
Interesting. 

The newly merged https://github.com/jaraco/skeleton/commit/63535c6efd3516a7ef35c862c24ef5b6d43c8494 introduced reliance on the default package discovery that was throttled because of the local setting `py_modules = pip-run` (according to https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#automatic-discovery, section `Important`, that setting disables automatic discovery). As a follow-up to https://github.com/jaraco/pip-run/actions/runs/7822456163/job/21341535125, 66e3ea2 was made. However, as you can see in the job logs for that commit (https://github.com/jaraco/pip-run/actions/runs/7833986829/job/21376230639), `autodoc` was unable to resolve modules in the wheel produced with the new `setup.cfg`.

I am not completely sure I understand the cause correctly, but removing `py_modules` setting from `setup.cfg` and reverting e186995 seemed to have fixed the issue (`tox -e docs` succeeds) without erroneously adding `tests` and `docs` to the wheel.

**Comment by jaraco** [comment] 2024-02-09 19:27
> removing `py_modules` setting from `setup.cfg`

I'm pretting sure removing `py_modules` would break `py -m pip-run`.

Probably the docs and tests exclusions need to be re-added to every project until another build system can be adopted that can more readily handle more than the simplest cases with default exclusions.

**Comment by mtelka** [comment] 2024-02-10 12:59
It looks like `pip-run` is not the only project with similar issue: https://github.com/pypa/pipenv/issues/5937

**Comment by jaraco** [comment] 2024-02-10 14:18
I suspect I made the same mistake with setuptools itself.

**Closed** 2024-02-10 14:22 UTC

**Comment by jaraco** [comment] 2024-02-10 14:44
Fix released in v12.6.1.
